package graphics;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import objects.UITutorial;
import logic.Integrator;

public class UISlider extends UIComponent{
	public boolean clicked = false;
	public Color green = new Color(150, 212, 144);
	public Color red = new Color(242, 102, 102);
	private float percentage = 1;
	public boolean disabled = false;
	private float upInterval = 0.01f;
	private float downInterval = 0.01f;
	/**
	 * UISlider constructor
	 * @param xPos The X position
	 * @param yPos The Y position
	 * @param x1 The width
	 * @param y1 The height
	 */
	public UISlider(int xPos, int yPos, int x1, int y1) {
		y_displace=84;//Default for this obj
		this.xSize = x1;
		this.ySize = y1;
		this.x = xPos;
		this.y = yPos;
		bounds = new Rectangle(x, y, xSize, ySize);
		setFontSize(70);
		mouse = new MouseAdapter(){
			int nx;
			int ny;
			@Override
			public void mousePressed(MouseEvent e) {
				if((!Integrator.paused||usable) && visible && bounds.contains(e.getPoint())){
					nx = e.getX() - x;
					ny = e.getY() - y;
					active = true;
				}else{
					active = false;
				}
			}
			@Override
			public void mouseDragged(MouseEvent e) {
				if(movable && usable() && bounds.contains(e.getPoint())){
					setBounds(e.getX() - nx, e.getY() - ny);
				}
			}
			@Override
			public void mouseClicked(MouseEvent e) {
				if(usable() && bounds.contains(e.getPoint())){
					clicked = true;
					active = true;
				}else{
					active = false;
				}
			}
			@Override
			public void mouseMoved(MouseEvent e) {
				if(visible && bounds.contains(e.getPoint())){
					if (!UITutorial.reactorTutorialOn && !UITutorial.turbineTutorialOn && !UITutorial.pumpTutorialOn) //this was messing with the color changes in the tutorial
						color = new Color(204, 204, 255);
				}else if(visible){
					if (!UITutorial.reactorTutorialOn && !UITutorial.turbineTutorialOn && !UITutorial.pumpTutorialOn) //this was messing with the color changes in the tutorial
						color = new Color(174, 174, 207);
				}
			}
			@Override
			public void mouseEntered(MouseEvent e) {}
			@Override
			public void mouseExited(MouseEvent e) {}
			@Override
			public void mouseReleased(MouseEvent e) {}
		};
		key = new KeyAdapter(){
			public void keyPressed(KeyEvent e) {
				
				if(usable() && !disabled && e.getKeyCode() == KeyEvent.VK_UP){
					if(percentage + 0.01 <=1){
						percentage += upInterval;
					}else{
						percentage = 1f;
					}
				}
				if(usable() && !disabled && e.getKeyCode() == KeyEvent.VK_DOWN){
					if(percentage - 0.01 >=0){
						percentage -= downInterval;
					}else{
						percentage = 0f;
					}
				}
			}
		};
	}
	/**
	 * Draws the object
	 */
	public void drawObj(Graphics2D g) {
		if(visible){
			Font oldFont = g.getFont();
			Color oldColor = g.getColor();//Saves previous information
				
			g.setColor(Color.black);
			g.fillRect(x, y, xSize, ySize);
				
			g.setColor(color);
			g.setFont(font);
			g.setStroke(new BasicStroke(5));
			g.fillRect(x+2, y+2, xSize-4, ySize-4);
				
			//Draws slider
			g.setColor(red);
			g.fillRect(x+20, y+20, xSize-40, ySize-40);
			
			g.setColor(green);
			g.fillRect(x+20, y+20, (int)((xSize-40)*percentage), ySize-40);
			//Draws slider
			
			if(text!=null){
				g.setColor(textColor);
				g.drawString(text, x+x_displace, y+y_displace);
				//System.out.println((int)(y+84+ySize/2.0));
			}
			g.setColor(oldColor);
			g.setFont(oldFont);//Restores previous information
		}
	}
	/**
	 * Sets the X + Y and updates the hitbox
	 * @param x The new X coordinate
	 * @param y The new Y coordinate
	 */
	public void setBounds(int x, int y){
		this.x = x;
		this.y = y;
		bounds = new Rectangle(x, y, xSize, ySize);
	}
	/**
	 * Returns the percentage that the slider is closer to the right
	 * @return A float that is 0 - 1, 0 = red slider, 1 = green slider
	 */
	public float getPercentage(){
		return percentage;
	}
	/**
	 * Set's the percentage of the slider
	 * @param per The float that the percentage will be set to. Must be between 0 and 1
	 */
	public void setPercentage(float per){
		if(per >=0 || per <=1){
			percentage = per;
		}
	}
	/**
	 * Limits how fast the user can move the slider in the positive direction
	 * @param up A positive float that will dictate how much it will move up
	 */
	public void setUpInterval(float up){
		upInterval = Math.abs(up);
	}
	/**
	 * Limits how fast the user can move the slider in the negative direction
	 * @param up A positive float that will dictate how much it will move down
	 */
	public void setDownInterval(float down){
		downInterval = Math.abs(down);
	}
	/**
	 * A method so that other components can interface with the slider in a way that the user would
	 * @param deltaTime The deltaTime passed into the update method, generated by the game loop
	 * @return A boolean value that says whether the value was moved
	 */
	public boolean down(long deltaTime){
		if(percentage - 0.01 >=0){
			percentage -= downInterval*4/deltaTime;
			return true;
		}else{
			percentage = 0f;
			return false;
		}
	}
	/**
	 * A method so that other components can interface with the slider in a way that the user would
	 * @param deltaTime The deltaTime passed into the update method, generated by the game loop
	 */
	public void up(long deltaTime){
		if(percentage + 0.01 <=1){
			percentage += upInterval*4/deltaTime;
		}else{
			percentage = 1f;
		}
	}

}

